# Generated by Django 6.0 on 2025-12-14 18:36

import relations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[relations.validators.validate_no_special_chars], verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[relations.validators.PriceRangeValidator(max_price=100000, min_price=10)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[relations.validators.validate_phone_format], verbose_name='Телефон'),
        ),
    ]
